// ============================================================
// FixFlow — Mock Data for Demo/Development Mode
// Used when Firebase is not yet configured
// ============================================================

import type {
  MaintenanceTicket,
  Property,
  Contractor,
  Notification,
  ActivityLog,
  DashboardMetrics,
  User,
} from '../types';

export const MOCK_PROPERTIES: Property[] = [
  {
    id: 'prop-001',
    name: 'Oakwood Apartments',
    address: '1234 Oak Street',
    city: 'Austin',
    state: 'TX',
    zipCode: '78701',
    managerId: 'manager-001',
    totalUnits: 48,
    propertyType: 'apartment',
    createdAt: '2024-01-15T10:00:00Z',
    updatedAt: '2024-01-15T10:00:00Z',
    isActive: true,
  },
  {
    id: 'prop-002',
    name: 'Riverside Condos',
    address: '567 River Drive',
    city: 'Austin',
    state: 'TX',
    zipCode: '78704',
    managerId: 'manager-001',
    totalUnits: 24,
    propertyType: 'condo',
    createdAt: '2024-02-01T10:00:00Z',
    updatedAt: '2024-02-01T10:00:00Z',
    isActive: true,
  },
  {
    id: 'prop-003',
    name: 'Maple Grove Homes',
    address: '890 Maple Ave',
    city: 'Austin',
    state: 'TX',
    zipCode: '78745',
    managerId: 'manager-001',
    totalUnits: 12,
    propertyType: 'house',
    createdAt: '2024-03-01T10:00:00Z',
    updatedAt: '2024-03-01T10:00:00Z',
    isActive: true,
  },
];

export const MOCK_CONTRACTORS: Contractor[] = [
  {
    id: 'cont-001',
    email: 'mike@plumbingpros.com',
    displayName: 'Mike Johnson',
    role: 'contractor',
    companyName: 'Plumbing Pros LLC',
    contactName: 'Mike Johnson',
    tradeTypes: ['plumbing'],
    phone: '(512) 555-0101',
    performanceRating: 4.8,
    totalJobsCompleted: 127,
    isAvailable: true,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
    isActive: true,
  },
  {
    id: 'cont-002',
    email: 'sarah@electricalexperts.com',
    displayName: 'Sarah Chen',
    role: 'contractor',
    companyName: 'Electrical Experts Inc',
    contactName: 'Sarah Chen',
    tradeTypes: ['electrical'],
    phone: '(512) 555-0102',
    performanceRating: 4.9,
    totalJobsCompleted: 89,
    isAvailable: true,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
    isActive: true,
  },
  {
    id: 'cont-003',
    email: 'tom@generalfix.com',
    displayName: 'Tom Williams',
    role: 'contractor',
    companyName: 'General Fix & Repair',
    contactName: 'Tom Williams',
    tradeTypes: ['general_repair', 'appliance'],
    phone: '(512) 555-0103',
    performanceRating: 4.5,
    totalJobsCompleted: 203,
    isAvailable: false,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
    isActive: true,
  },
  {
    id: 'cont-004',
    email: 'lisa@hvacspecialists.com',
    displayName: 'Lisa Martinez',
    role: 'contractor',
    companyName: 'HVAC Specialists',
    contactName: 'Lisa Martinez',
    tradeTypes: ['heating'],
    phone: '(512) 555-0104',
    performanceRating: 4.7,
    totalJobsCompleted: 156,
    isAvailable: true,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
    isActive: true,
  },
];

export const MOCK_TICKETS: MaintenanceTicket[] = [
  {
    id: 'ticket-001',
    ticketNumber: 'MT-2024-000001',
    tenantId: 'tenant-001',
    tenantName: 'James Wilson',
    propertyId: 'prop-001',
    propertyName: 'Oakwood Apartments',
    unitNumber: '2B',
    category: 'plumbing',
    priority: 'high',
    status: 'in_progress',
    title: 'Kitchen sink leaking under cabinet',
    description: 'There is a persistent leak under the kitchen sink. Water is pooling and causing damage to the cabinet floor.',
    attachments: [],
    assignedContractorId: 'cont-001',
    assignedContractorName: 'Mike Johnson',
    issueDuration: '1_3_days',
    contractorAccess: 'yes',
    isEmergency: false,
    isEscalated: false,
    createdAt: '2024-06-10T09:00:00Z',
    updatedAt: '2024-06-11T14:30:00Z',
    scheduledDate: '2024-06-14T10:00:00Z',
  },
  {
    id: 'ticket-002',
    ticketNumber: 'MT-2024-000002',
    tenantId: 'tenant-002',
    tenantName: 'Maria Garcia',
    propertyId: 'prop-001',
    propertyName: 'Oakwood Apartments',
    unitNumber: '4A',
    category: 'electrical',
    priority: 'emergency',
    status: 'assigned',
    title: 'Power outlet sparking in bedroom',
    description: 'The outlet near the bed is sparking when I plug in devices. Very concerned about fire hazard.',
    attachments: [],
    assignedContractorId: 'cont-002',
    assignedContractorName: 'Sarah Chen',
    issueDuration: 'today',
    contractorAccess: 'contact_first',
    isEmergency: true,
    isEscalated: false,
    createdAt: '2024-06-12T16:45:00Z',
    updatedAt: '2024-06-12T17:00:00Z',
  },
  {
    id: 'ticket-003',
    ticketNumber: 'MT-2024-000003',
    tenantId: 'tenant-003',
    tenantName: 'David Kim',
    propertyId: 'prop-002',
    propertyName: 'Riverside Condos',
    unitNumber: '1C',
    category: 'heating',
    priority: 'medium',
    status: 'submitted',
    title: 'HVAC not cooling properly',
    description: 'The air conditioning unit is running but not cooling the apartment. Temperature stays above 80°F even with thermostat set to 68°F.',
    attachments: [],
    issueDuration: '1_week',
    contractorAccess: 'yes',
    isEmergency: false,
    isEscalated: false,
    createdAt: '2024-06-11T11:20:00Z',
    updatedAt: '2024-06-11T11:20:00Z',
  },
  {
    id: 'ticket-004',
    ticketNumber: 'MT-2024-000004',
    tenantId: 'tenant-001',
    tenantName: 'James Wilson',
    propertyId: 'prop-001',
    propertyName: 'Oakwood Apartments',
    unitNumber: '2B',
    category: 'general_repair',
    priority: 'low',
    status: 'completed',
    title: 'Broken door handle on bathroom',
    description: 'The door handle on the bathroom door is loose and sometimes gets stuck.',
    attachments: [],
    assignedContractorId: 'cont-003',
    assignedContractorName: 'Tom Williams',
    issueDuration: 'more_than_1_week',
    contractorAccess: 'yes',
    isEmergency: false,
    isEscalated: false,
    createdAt: '2024-06-05T08:00:00Z',
    updatedAt: '2024-06-08T15:00:00Z',
    resolvedAt: '2024-06-08T15:00:00Z',
  },
  {
    id: 'ticket-005',
    ticketNumber: 'MT-2024-000005',
    tenantId: 'tenant-004',
    tenantName: 'Emma Thompson',
    propertyId: 'prop-003',
    propertyName: 'Maple Grove Homes',
    unitNumber: '1',
    category: 'roofing',
    priority: 'high',
    status: 'under_review',
    title: 'Roof leak above living room',
    description: 'After the recent rain, there is a water stain on the ceiling and active dripping when it rains.',
    attachments: [],
    issueDuration: '1_3_days',
    contractorAccess: 'yes',
    isEmergency: false,
    isEscalated: true,
    createdAt: '2024-06-09T14:00:00Z',
    updatedAt: '2024-06-10T09:00:00Z',
  },
  {
    id: 'ticket-006',
    ticketNumber: 'MT-2024-000006',
    tenantId: 'tenant-005',
    tenantName: 'Robert Brown',
    propertyId: 'prop-002',
    propertyName: 'Riverside Condos',
    unitNumber: '3D',
    category: 'pest_control',
    priority: 'medium',
    status: 'scheduled',
    title: 'Cockroach infestation in kitchen',
    description: 'Seeing multiple cockroaches in the kitchen, especially at night. Need pest control urgently.',
    attachments: [],
    assignedContractorId: 'cont-003',
    assignedContractorName: 'Tom Williams',
    issueDuration: '1_week',
    contractorAccess: 'yes',
    isEmergency: false,
    isEscalated: false,
    createdAt: '2024-06-08T10:30:00Z',
    updatedAt: '2024-06-10T11:00:00Z',
    scheduledDate: '2024-06-15T09:00:00Z',
  },
];

export const MOCK_NOTIFICATIONS: Notification[] = [
  {
    id: 'notif-001',
    userId: 'manager-001',
    ticketId: 'ticket-002',
    ticketNumber: 'MT-2024-000002',
    event: 'ticket_submitted',
    title: 'Emergency Ticket Submitted',
    message: 'Maria Garcia reported an emergency electrical issue at Oakwood Apartments, Unit 4A.',
    isRead: false,
    createdAt: '2024-06-12T16:45:00Z',
    actionUrl: '/manager/tickets/ticket-002',
  },
  {
    id: 'notif-002',
    userId: 'manager-001',
    ticketId: 'ticket-005',
    ticketNumber: 'MT-2024-000005',
    event: 'ticket_escalated',
    title: 'Ticket Escalated',
    message: 'Ticket MT-2024-000005 (Roof leak) has been escalated and requires immediate attention.',
    isRead: false,
    createdAt: '2024-06-10T09:00:00Z',
    actionUrl: '/manager/tickets/ticket-005',
  },
  {
    id: 'notif-003',
    userId: 'manager-001',
    ticketId: 'ticket-004',
    ticketNumber: 'MT-2024-000004',
    event: 'job_completed',
    title: 'Job Completed',
    message: 'Tom Williams has marked ticket MT-2024-000004 as completed.',
    isRead: true,
    createdAt: '2024-06-08T15:00:00Z',
    actionUrl: '/manager/tickets/ticket-004',
  },
];

export const MOCK_ACTIVITY_LOGS: ActivityLog[] = [
  {
    id: 'log-001',
    ticketId: 'ticket-001',
    userId: 'manager-001',
    userName: 'Alex Morgan',
    userRole: 'property_manager',
    action: 'Assigned contractor',
    previousStatus: 'under_review',
    newStatus: 'assigned',
    details: 'Assigned to Mike Johnson (Plumbing Pros LLC)',
    createdAt: '2024-06-11T10:00:00Z',
  },
  {
    id: 'log-002',
    ticketId: 'ticket-001',
    userId: 'manager-001',
    userName: 'Alex Morgan',
    userRole: 'property_manager',
    action: 'Status updated',
    previousStatus: 'assigned',
    newStatus: 'scheduled',
    details: 'Scheduled for June 14, 2024 at 10:00 AM',
    createdAt: '2024-06-11T14:30:00Z',
  },
  {
    id: 'log-003',
    ticketId: 'ticket-001',
    userId: 'cont-001',
    userName: 'Mike Johnson',
    userRole: 'contractor',
    action: 'Work started',
    previousStatus: 'scheduled',
    newStatus: 'in_progress',
    details: 'Arrived on site, began assessment of plumbing issue',
    createdAt: '2024-06-14T10:15:00Z',
  },
];

export const MOCK_DASHBOARD_METRICS: DashboardMetrics = {
  openTickets: 18,
  assignedTickets: 7,
  inProgressTickets: 4,
  overdueTickets: 3,
  completedTickets: 42,
  emergencyTickets: 2,
  avgResolutionDays: 3.2,
  totalThisMonth: 23,
};

export const MOCK_MONTHLY_DATA = [
  { month: 'Jan', tickets: 18, completed: 15 },
  { month: 'Feb', tickets: 22, completed: 20 },
  { month: 'Mar', tickets: 19, completed: 18 },
  { month: 'Apr', tickets: 25, completed: 22 },
  { month: 'May', tickets: 21, completed: 19 },
  { month: 'Jun', tickets: 23, completed: 12 },
];

export const MOCK_CATEGORY_DATA = [
  { category: 'Plumbing', count: 28, color: '#0D9488' },
  { category: 'Electrical', count: 18, color: '#0EA5E9' },
  { category: 'Heating', count: 15, color: '#F59E0B' },
  { category: 'General Repair', count: 22, color: '#6366F1' },
  { category: 'Roofing', count: 8, color: '#EF4444' },
  { category: 'Pest Control', count: 5, color: '#8B5CF6' },
  { category: 'Appliance', count: 12, color: '#EC4899' },
  { category: 'Other', count: 4, color: '#94A3B8' },
];

// Demo users for login
export const DEMO_USERS: Array<{ email: string; password: string; role: string; name: string }> = [
  { email: 'tenant@demo.com', password: 'demo1234', role: 'tenant', name: 'James Wilson' },
  { email: 'manager@demo.com', password: 'demo1234', role: 'property_manager', name: 'Alex Morgan' },
  { email: 'contractor@demo.com', password: 'demo1234', role: 'contractor', name: 'Mike Johnson' },
  { email: 'admin@demo.com', password: 'demo1234', role: 'admin', name: 'Admin User' },
];

import type { TicketMessage } from '../types';

export const MOCK_MESSAGES: TicketMessage[] = [
  {
    id: 'msg-001',
    ticketId: 'ticket-001',
    senderId: 'tenant-001',
    senderName: 'James Wilson',
    senderRole: 'tenant',
    content: 'The kitchen sink has been leaking for two days now. Water is pooling under the cabinet.',
    isRead: true,
    createdAt: '2024-06-10T09:00:00Z',
  },
  {
    id: 'msg-002',
    ticketId: 'ticket-001',
    senderId: 'manager-001',
    senderName: 'Alex Morgan',
    senderRole: 'property_manager',
    content: 'Hi James, thank you for reporting this. I\'ve assigned a plumber who will visit on June 14th between 10 AM and 12 PM. Please ensure someone is home.',
    isRead: true,
    createdAt: '2024-06-11T10:30:00Z',
  },
  {
    id: 'msg-003',
    ticketId: 'ticket-001',
    senderId: 'cont-001',
    senderName: 'Mike Johnson',
    senderRole: 'contractor',
    content: 'Hello! I\'ll be arriving around 10 AM on the 14th. I\'ll need access to the kitchen and the water shutoff valve. Do you know where it\'s located?',
    isRead: true,
    createdAt: '2024-06-12T14:00:00Z',
  },
  {
    id: 'msg-004',
    ticketId: 'ticket-001',
    senderId: 'tenant-001',
    senderName: 'James Wilson',
    senderRole: 'tenant',
    content: 'The shutoff is in the utility closet near the front door. I\'ll be home all morning.',
    isRead: false,
    createdAt: '2024-06-12T15:30:00Z',
  },
  {
    id: 'msg-005',
    ticketId: 'ticket-002',
    senderId: 'tenant-002',
    senderName: 'Sarah Chen',
    senderRole: 'tenant',
    content: 'The circuit breaker keeps tripping in the living room. It\'s happened 3 times today.',
    isRead: true,
    createdAt: '2024-06-09T11:00:00Z',
  },
  {
    id: 'msg-006',
    ticketId: 'ticket-002',
    senderId: 'manager-001',
    senderName: 'Alex Morgan',
    senderRole: 'property_manager',
    content: 'Sarah, this sounds like it could be a safety issue. I\'m escalating this to high priority and will have an electrician contact you today.',
    isRead: true,
    createdAt: '2024-06-09T11:45:00Z',
  },
];
